import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css'
import Layout, { siteTitle } from '../components/layout'
import TableCells from '../components/table-cells'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nathan's Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.sectionBorderBox}>
          <h1 className={styles.header}>
            Chun Yin, Yung
            <br />
          </h1>
          
          <h2 className={utilStyles.headingLg}>Nathan</h2>

          <p className={styles.description}>
            <code className={styles.code}>AWS Certified Developer Associate {'&'} Graduate of Lancaster University</code>
          </p>
        </section>
        
        <section className={styles.sectionBorderBox}>
          <Image
            priority
            src="/images/aws-certified-developer-associate.png"
            className={utilStyles.borderCircle}
            height={'auto'}
            width={144}
            alt={'nathan'}
          />
        </section>
        

        
        <div className={styles.sectionBorderBox}>
          <p className={utilStyles.headingLg}>
            Main Skills
          </p>
        </div>

        <TableCells />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
